version: '3.4'

services:

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "8080:80"
      - "8081:81"
    volumes:
      - ./etc/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./api:/app
    depends_on:
      - php
      - ionic

  ionic:
    build:
      context: ./etc/dev/ionic/
    ports:
      - "8100:8100"
      - "35729:35729"
    volumes:
      - ./client:/myApp
    command: ["ionic", "serve"]

  php:
    build:
      context: ./etc/dev/php/
    ports:
      - "2323:22"
    volumes:
      - ./api:/app